id: ADA00B05C
title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
type: translation
pechas:
- IB6BAF87C
- I065337C3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:11.452379
  last_modified_at: 2023-01-04 12:11:11.452385
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IB6BAF87C/BDCA: BF21
  I065337C3/F4F9: BF21
